#include "device.h"

struct class_map pci_class_names[] = {
    {UNCLASSIFIED, "UNCLASSIFIED"},
    {STORAGE_CONTROLLER, "STORAGE"},
    {NETWORK_CONTROLLER, "NETWORK"},
    {DISPLAY_CONTROLLER, "DISPLAY"},
    {MULTIMEDIA_CONTROLLER, "MULTIMEDIA"},
    {MEMORY_CONTROLLER, "MEMORY"},
    {BRIDGE, "BRIDGE"},
    {SIMPLE_COMMUNICATION_CONTROLLER, "SIMPLE_COMMUNICATION"},
    {BASE_SYSTEM_PERIPHERAL, "BASE_SYSTEM_PERIPHERAL"},
    {INPUT_DEVICE_CONTROLLER, "INPUT_DEVICE"},
    {DOCKING_STATION, "DOCKING_STATION"},
    {PROCESSOR, "PROCESSOR"},
    {SERIAL_BUS_CONTROLLER, "SERIAL_BUS"},
    {WIRELESS_CONTROLLER, "WIRELESS"},
    {INTELLIGENT_CONTROLLER, "INTELLIGENT"},
    {SATELLITE_COMMUNICATION_CONTROLLER, "SATELLITE_COMMUNICATION"},
    {ENCRYPTION_CONTROLLER, "ENCRYPTION"},
    {SIGNAL_PROCESSING_CONTROLLER, "SIGNAL_PROCESSING"},
    {PROCESSING_ACCELERATOR, "PROCESSING_ACCELERATOR"},
    {NON_ESSENTIAL_INSTRUMENTATION, "NON_ESSENTIAL_INSTRUMENTATION"},
    {UNASSIGNED_CLASS, "UNASSIGNED_CLASS"},
    {0, 0} // маркер конца
};


struct subclass_map pci_subclass_storage_names[] = {
    {STORAGE_CONTROLLER, STORAGE_SCSI_BUS_CONTROLLER, "SCSI_BUS_CONTROLLER"},
    {STORAGE_CONTROLLER, STORAGE_IDE_CONTROLLER, "IDE_CONTROLLER"},
    {STORAGE_CONTROLLER, STORAGE_FLOPPY_DISK_CONTROLLER, "FLOPPY_DISK_CONTROLLER"},
    {STORAGE_CONTROLLER, STORAGE_IPI_BUS_CONTROLLER, "IPI_BUS_CONTROLLER"},
    {STORAGE_CONTROLLER, STORAGE_RAID_CONTROLLER, "RAID_CONTROLLER"},
    {STORAGE_CONTROLLER, STORAGE_ATA_CONTROLLER, "ATA_CONTROLLER"},
    {STORAGE_CONTROLLER, STORAGE_SERIAL_ATA_CONTROLLER, "SERIAL_ATA_CONTROLLER"},
    {STORAGE_CONTROLLER, STORAGE_SERIAL_ATTACHED_SCSI, "SERIAL_ATTACHED_SCSI"},
    {STORAGE_CONTROLLER, STORAGE_NON_VOLATILE_MEMORY, "NON_VOLATILE_MEMORY"},
    {STORAGE_CONTROLLER, STORAGE_OTHER, "OTHER"},
    {0, 0, 0} // маркер конца
};

struct subclass_map pci_subclass_network_names[] = {
    {NETWORK_CONTROLLER, NETWORK_ETHERNET_CONTROLLER, "ETHERNET_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_TOKEN_RING_CONTROLLER, "TOKEN_RING_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_FDDI_CONTROLLER, "FDDI_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_ATM_CONTROLLER, "ATM_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_ISDN_CONTROLLER, "ISDN_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_WORLDFIP_CONTROLLER, "WORLDFIP_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_PICMG_MC_CONTROLLER, "PICMG_MC_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_INFINIBAND_CONTROLLER, "INFINIBAND_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_FABRIC_CONTROLLER, "FABRIC_CONTROLLER"},
    {NETWORK_CONTROLLER, NETWORK_OTHER, "OTHER"},
    {0, 0, 0} // маркер конца
};

struct subclass_map pci_subclass_display_names[] = {
    {DISPLAY_CONTROLLER, DISPLAY_VGA_COMPATIBLE, "VGA_COMPATIBLE"},
    {DISPLAY_CONTROLLER, DISPLAY_XGA, "XGA"},
    {DISPLAY_CONTROLLER, DISPLAY_3D, "3D"},
    {DISPLAY_CONTROLLER, DISPLAY_OTHER, "OTHER"},
    {0, 0, 0} // маркер конца
};

struct subclass_map pci_subclass_multimedia_names[] = {
    {MULTIMEDIA_CONTROLLER, MULTIMEDIA_VIDEO, "VIDEO"},
    {MULTIMEDIA_CONTROLLER, MULTIMEDIA_AUDIO, "AUDIO"},
    {MULTIMEDIA_CONTROLLER, MULTIMEDIA_TELEPHONY, "TELEPHONY"},
    {MULTIMEDIA_CONTROLLER, MULTIMEDIA_AUDIO_DEVICE, "AUDIO_DEVICE"},
    {MULTIMEDIA_CONTROLLER, MULTIMEDIA_AUDIO_DEVICE, "OTHER"},
    {0, 0, 0} // маркер конца
};

struct subclass_map pci_subclass_memory_names[] = {
    {MEMORY_CONTROLLER, MEMORY_RAM, "RAM"},
    {MEMORY_CONTROLLER, MEMORY_FLASH, "FLASH"},
    {MEMORY_CONTROLLER, MEMORY_OTHER, "OTHER"},
    {0, 0, 0} // маркер конца
};

struct subclass_map pci_subclass_bridge_names[] = {
    {BRIDGE, BRIDGE_HOST, "HOST"},
    {BRIDGE, BRIDGE_ISA, "ISA"},
    {BRIDGE, BRIDGE_EISA, "EISA"},
    {BRIDGE, BRIDGE_MCA, "MCA"},
    {BRIDGE, BRIDGE_PCI_TO_PCI, "PCI_TO_PCI"},
    {BRIDGE, BRIDGE_PCMCIA, "PCMCIA"},
    {BRIDGE, BRIDGE_NUBUS, "NUBUS"},
    {BRIDGE, BRIDGE_CARDBUS, "CARDBUS"},
    {BRIDGE, BRIDGE_RACEWAY, "RACEWAY"},
    {BRIDGE, BRIDGE_PCI_TO_PCI1, "PCI_TO_PCI1"},
    {BRIDGE, BRIDGE_INFINIBAND_TO_PCI, "INFINIBAND_TO_PCI"},
    {BRIDGE, BRIDGE_OTHER, "OTHER"},
    {0, 0, 0} // маркер конца
};


struct subclass_map* pci_subclass_names[] = {
    pci_subclass_storage_names,
    pci_subclass_network_names,
    pci_subclass_display_names,
    pci_subclass_multimedia_names,
    pci_subclass_memory_names,
    pci_subclass_bridge_names,
    0
};
