include ../../../common.mk

DRIVER_NAME := display
OBJ_DIR     := ../../../output/drivers/$(DRIVER_NAME)

all:
	mkdir -p $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $(DRIVER_NAME).c -o $(OBJ_DIR)/$(DRIVER_NAME).o
